### ISSUE TITLE
Fine Preprocess feature size.

### ISSUE THREAD

**Issue by AliYoussef97** [zju3dv/EfficientLoFTR#11]
Hello!

I had a brief question regarding image_1's fine features' dimention, in particular the addtion of +2 when unfolding the local windows [here](https://github.com/zju3dv/EfficientLoFTR/blob/debdc19c32d656734f92052f30b7e366d903796b/src/loftr/loftr_module/fine_preprocess.py#L105C13-L106C80). I fail to understand the reasoning behind the +2, as along the pipeline `conf_matrix_ff` has a size of `[M,W**2, (W+2)**2]` [here](https://github.com/zju3dv/EfficientLoFTR/blob/debdc19c32d656734f92052f30b7e366d903796b/src/loftr/utils/fine_matching.py#L53C13-L53C26). Although `softmax_matrix_f` does become `[M,WW,WW]`, conf_matrix_ff is stored as  `[M,W**2, (W+2)**2]`.

Would really appreciate if you could provide an explanation for the +2.

Thank you!

**Comment by wyf2020** [comment]
Sorry for the late reply. This is a great question! The "+2" is due to our two-stage refinement process. In the first stage, we crop non-overlapping 8x8 fine windows from both images to compute the argmax confidence. In the second stage, we then crop 3x3 local windows around the argmax confidence areas in the right image. If the argmax from the first stage is located at the edge of an 8x8 window, the second stage needs to crop 3x3 local windows from 10x10 fine windows in the right image. Since the 8x8 fine windows do not overlap, we cannot adjust by padding zero in the 3x3 local windows or discarding edge argmaxes. Therefore, in the fine preprocess, we unfold 10x10 fine windows in the right image in advance for use in the second stage.

**Comment by AliYoussef97** [comment]
@wyf2020 Thank you so much this makes so much sense! 

Just for clarification, $8 \times 8$ window -> `softmax_matrix_f `- > `get_fine_ds_match` to get the the keypoints from $8 \times 8$ window. Following that, keypoints -> get $3 \times 3$ local window from `conf_matrix_ff ` centered around the pixel-level keypoints. I hope my understanding is correct?

**Comment by wyf2020** [comment]
Yes, exactly! Your understanding is correct.

**Comment by AliYoussef97** [comment]
@wyf2020 Thank you so much!

**Comment by chenxianbo** [comment]
> Sorry for the late reply. This is a great question! The "+2" is due to our two-stage refinement process. In the first stage, we crop non-overlapping 8x8 fine windows from both images to compute the argmax confidence. In the second stage, we then crop 3x3 local windows around the argmax confidence areas in the right image. If the argmax from the first stage is located at the edge of an 8x8 window, the second stage needs to crop 3x3 local windows from 10x10 fine windows in the right image. Since the 8x8 fine windows do not overlap, we cannot adjust by padding zero in the 3x3 local windows or discarding edge argmaxes. Therefore, in the fine preprocess, we unfold 10x10 fine windows in the right image in advance for use in the second stage.

第一阶段获取的索引是在W*W的1D索引，在第二阶段是已经是(W+2)*(W+2).
”idx_r_iids, idx_jids = idx_r / W,    idx_r % W“后面是不是各要+1，转换到(W+2)*(W+2)中的索引
