### ISSUE TITLE
Export to ONNX 

### ISSUE THREAD

**Issue by williamhoole** [zju3dv/EfficientLoFTR#12]
Hi, 

Is it possible to export the model to ONNX ?

**Comment by wyf2020** [comment]
Hi,

I believe it is possible to export the model to ONNX since our model doesn't involve any necessary dynamic control flow, and all the PyTorch functions we used are common. However, we currently do not have plans to offer an ONNX version because we lack experience with ONNX optimization. We would very much welcome any attempts to try this out.

**Comment by williamhoole** [comment]
Hi thank you very much for your reply! I have found a repository that converts the original LOFTR to ONNX. This should also work for EfficientLoFTR. I will try adjust the code for this repository. Here is the link: [loftr2onnx](https://github.com/oooooha/loftr2onnx)

**Comment by rebmaso** [comment]
@williamhoole did you manage to adapt the exporter to eloftr? I managed to get an .onnx after some minor tweaks in the forward, but the onnx inference fails bc of size mismatches. Thanks!

**Comment by klein0809** [comment]
> @williamhoole did you manage to adapt the exporter to eloftr? I managed to get an .onnx after some minor tweaks in the forward, but the onnx inference fails bc of size mismatches. Thanks!

hello, have you solved this problem? I have the same problem

**Comment by samwarren** [comment]
also checking into see if anyone (@williamhoole) has converted eloftr to .onnx successfully?
