### ISSUE TITLE
Output descriptors

### ISSUE THREAD

**Issue by chenjiajie9811** [zju3dv/EfficientLoFTR#20]
Hi there, 

thank you for your great work! I am wondering whether you can kindly provide the possibility to get access to the descriptor of each matched keypoint? I would appreciate it a lot!

**Comment by wyf2020** [comment]
Hi,

Thank you for your suggestion! However, since our work is detector-free, there is no uniquely defined descriptor. For the position of a matching point, we can provide three types of local features: 
(1) [coarse feature (1/8 resolution) before the transformer](https://github.com/zju3dv/EfficientLoFTR/blob/68eb9218c1bdd179db9a07ad4771161b198d98b3/src/loftr/loftr.py#L89); 
(2) [coarse feature (1/8 resolution) after the transformer](https://github.com/zju3dv/EfficientLoFTR/blob/68eb9218c1bdd179db9a07ad4771161b198d98b3/src/loftr/loftr.py#L89); 
(3) [fine feature (full resolution)](https://github.com/zju3dv/EfficientLoFTR/blob/68eb9218c1bdd179db9a07ad4771161b198d98b3/src/loftr/loftr.py#L109). 
You can freely choose one, part, or all of them and combine them by simply returning them at the end of forward function. Additionally, it should be noted that our (2) and (3) local features are conditioned on each pair of images. I am not sure what you need the descriptor for. If you need to use a descriptor for SFM (Structure from Motion), I recommend directly using our [SFM framework](https://github.com/zju3dv/DetectorFreeSfM) designed specifically for detector-free matching. If you need to use a descriptor for other multiview purposes, additional descriptors aggregation of a single image conditioned on different pairs may be required.

**Comment by chenjiajie9811** [comment]
Thank you so much for the detailed reply! Oh I didn't notice the code of Detector-free SFM is released, that's amazing. Maybe I will have a look at that.
