### ISSUE TITLE
Question About Fine Supervision Code

### ISSUE THREAD

**Issue by szyfh** [zju3dv/EfficientLoFTR#41]
Thanks for you excellent works, I have a question about Fine Supervision Code

> In `spvs_fine` function 

this code `grid_pt0_f = create_meshgrid(hf0, wf0, False, device) - W // 2 + 0.5` move coordinate from top_left  to center, and warp coordinate to another image. Later you calculate `delta_w_pt0_i = w_pt0_i - pt1_i[b_ids, j_ids][:, None, :]`, but here `pt1_i` is top_left format and you move delta to center format by `delta_w_pt0_f = delta_w_pt0_i / scalei1[:, None, :] + W // 2 - 0.5`. So what is meaning of move format? Why not only use the top_left format?

**Comment by wyf2020** [comment]
Thank you for your question! 
We use `grid_pt0_f = create_meshgrid(hf0, wf0, False, device) - W // 2 + 0.5` and `delta_w_pt0_i = w_pt0_i - pt1_i[b_ids, j_ids][:, None, :]` because we use interpolation with align_corner=False when [obtaining the fine features](https://github.com/zju3dv/EfficientLoFTR/blob/a2ef8b0096df2dce9154fc8e48a53ff60cadf68b/src/loftr/loftr_module/fine_preprocess.py#L55). So when W=8, the fine_grid should have a 0.5 gap relative to the coarse_grid delta, like this `[[(-3.5,-3.5),(-2.5,-3.5),...,(3.5,-3.5),],[(-3.5,-2.5),(-2.5,-2.5),...,(3.5,-2.5)],...,[(-3.5,3.5),(-2.5,3.5),...,(3.5,3.5)]]`. 
We use `delta_w_pt0_f = delta_w_pt0_i / scalei1[:, None, :] + W // 2 - 0.5` to facilitate the [subsequent use of round](https://github.com/zju3dv/EfficientLoFTR/blob/a2ef8b0096df2dce9154fc8e48a53ff60cadf68b/src/loftr/utils/supervision.py#L221) to get the fine_grid index.
